ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS allows_partial_payment BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS unit_name TEXT,
  ADD COLUMN IF NOT EXISTS total_units INTEGER,
  ADD COLUMN IF NOT EXISTS pay_per_unit_inr DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS pay_per_unit_nc INTEGER;

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS valid_units INTEGER,
  ADD COLUMN IF NOT EXISTS partial_payment_nc INTEGER;
